### ISSUE TITLE
Add SIP error codes

### ISSUE THREAD

**Issue by noxone** [noxone/error-codes-viewer#27]
https://en.wikipedia.org/wiki/List_of_SIP_response_codes

**Comment by lars-sh** [comment]
Probably the best origin for SIP response codes is https://tools.ietf.org/html/rfc3261#section-21

**Comment by noxone** [comment]
lars-sh said: Probably the best origin for SIP response codes is https://tools.ietf.org/html/rfc3261#section-21

**Comment by lars-sh** [comment]
@noxone , I like the RFC descriptions better, while Wikipedia contains some additional response codes, such as 494, which has been standardized in another RFC.

**Comment by noxone** [comment]
OK, thanks for the info
